"""baseline: users, profiles, jobs, applications, resume_facts

Revision ID: 0001
Revises:
Create Date: 2026-08-15

Hand-written, not autogenerated — no live Postgres available to diff against
(Docker install pending approval, DEPENDENCIES.md §5). Mirrors models.py exactly;
re-generate with `alembic revision --autogenerate` once a real Postgres exists,
and diff the result against this file before trusting it.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )

    op.create_table(
        "profiles",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("persona", sa.Enum("developer", "product_manager", "marketing", name="persona"), nullable=False),
        sa.Column("headline", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("prefs", postgresql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.UniqueConstraint("user_id", "persona", name="uq_profile_user_persona"),
    )

    op.create_table(
        "jobs",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("company", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("remote", sa.Boolean(), nullable=True),
        sa.Column("salary", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("apply_url", sa.String(), nullable=False),
        sa.Column("tags", postgresql.JSON(), nullable=True),
        sa.Column("posted_at", sa.DateTime(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=True),
        sa.UniqueConstraint("source", "external_id", name="uq_job_source_external_id"),
    )

    op.create_table(
        "applications",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("profile_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("profiles.id", ondelete="CASCADE"), nullable=False),
        sa.Column("job_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("jobs.id"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("saved", "applied", "oa", "recruiter", "interview", "offer", "rejected", name="applicationstatus"),
            nullable=True,
        ),
        sa.Column("portal", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tailored_resume_json", postgresql.JSON(), nullable=True),
        sa.Column("tailored_cover_letter", sa.Text(), nullable=True),
        sa.Column("applied_at", sa.DateTime(), nullable=True),
        sa.Column("next_follow_up_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.UniqueConstraint("profile_id", "job_id", name="uq_application_profile_job"),
    )

    op.create_table(
        "resume_facts",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("profile_id", postgresql.UUID(as_uuid=False), sa.ForeignKey("profiles.id", ondelete="CASCADE"), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("achievement", sa.Text(), nullable=False),
        sa.Column("proof", sa.Text(), nullable=True),
        sa.Column("metric", sa.String(), nullable=True),
        sa.Column("tags", postgresql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )


def downgrade() -> None:
    op.drop_table("resume_facts")
    op.drop_table("applications")
    op.drop_table("jobs")
    op.drop_table("profiles")
    op.drop_table("users")
    op.execute("DROP TYPE IF EXISTS applicationstatus")
    op.execute("DROP TYPE IF EXISTS persona")
